version: '3'
services:
  client:
    build: ./Client
    ports:
      - '80:80'
    depends_on:
      - server
  server:
    build: ./Server
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'

